# Generated by Django 2.1.1 on 2018-12-05 14:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BFM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bfm_rq_txt', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[('Finished', 'Finished'), ('Running', 'Running'), ('NotStarted', 'NotStarted')], max_length=27)),
                ('response_time', models.IntegerField(null=True)),
                ('payload_size', models.IntegerField(null=True)),
                ('bfm_rq_file', models.FileField(blank=True, upload_to='')),
                ('bfm_rs_file', models.FileField(upload_to='')),
                ('df_path', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DashApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('base_state', models.TextField(default='{}')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('save_on_change', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StatelessApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dashapp',
            name='stateless_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new_dash.StatelessApp'),
        ),
    ]
