# Generated by Django 2.1.1 on 2018-12-14 14:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_dash', '0002_several_same_bfm'),
    ]

    operations = [
        migrations.CreateModel(
            name='fare_forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('ond', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^([A-Z]{3}-[A-Z]{3},)*([A-Z]{3}-[A-Z]{3})+$', 'Check!')])),
                ('departure_date', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^([A-Z]{3}-[A-Z]{3},)*([A-Z]{3}-[A-Z]{3})+$', 'Check!')])),
                ('return_date', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^([A-Z]{3}-[A-Z]{3},)*([A-Z]{3}-[A-Z]{3})+$', 'Check!')])),
                ('predict_date', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^([A-Z]{3}-[A-Z]{3},)*([A-Z]{3}-[A-Z]{3})+$', 'Check!')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='several_same_bfm',
            name='onds',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^([A-Z]{3}-[A-Z]{3},)*([A-Z]{3}-[A-Z]{3})+$', 'Check!')]),
        ),
    ]
