# Generated by Django 2.1.1 on 2019-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_dash', '0003_auto_20181214_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='OceanAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fare_forecast',
            name='departure_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fare_forecast',
            name='predict_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fare_forecast',
            name='return_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
