# Generated by Django 2.1.1 on 2019-01-30 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_dash', '0004_auto_20190115_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualInterlining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ori', models.CharField(max_length=3)),
                ('des', models.CharField(max_length=3)),
                ('ddate', models.CharField(max_length=20)),
                ('rdate', models.CharField(max_length=20)),
                ('stayover', models.CharField(max_length=20)),
                ('night_penaly', models.IntegerField()),
                ('analysis_finished', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
