# Generated by Django 2.1.1 on 2019-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_dash', '0006_auto_20190130_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualinterlining',
            name='author',
        ),
        migrations.AlterField(
            model_name='virtualinterlining',
            name='night_penaly',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='virtualinterlining',
            name='stayover',
            field=models.IntegerField(default=2),
        ),
    ]
